export const OFFICIAL_IMAGES: Record<string, string> = {
  "Abby Cadabby": "https://sesameworkshop.org/wp-content/uploads/2023/03/Abby-1-667x500.png",
  "Bert": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_bert-750x416.png",
  "Big Bird": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_bigbird-750x416.png",
  "Cookie Monster": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_cookiemonster-750x416.png",
  "Count von Count": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_count-750x416.png",
  "Elmo": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_elmo-750x416.png",
  "Ernie": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_ernie-750x416.png",
  "Grover": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_grover-750x416.png",
  "Julia": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_julia-750x416.png",
  "Oscar": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_oscar-750x416.png",
  "Oscar the Grouch": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_oscar-750x416.png",
  "Rosita": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_rosita-750x416.png",
  "Snuffy": "https://sesameworkshop.org/wp-content/uploads/2023/03/Snuffy_bio-copy-667x500.jpg",
  "Zoe": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_zoe-750x416.png",
  "Baby Bear": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_babybear-750x416.png",
  "Gabrielle": "https://sesameworkshop.org/wp-content/uploads/2023/06/Gabrielle_Character-750x416.png",
  "Gonger": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_gonger-750x416.png",
  "Ji-Young": "https://sesameworkshop.org/wp-content/uploads/2023/03/Ji-Young.Character-750x416.jpeg",
  "Rudy": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_rudy-750x416.png",
  "Tamir": "https://sesameworkshop.org/wp-content/uploads/2023/02/Tamir-667x500.jpg",
  "Telly": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_telly-750x416.png",
  "Mr. Snuffleupagus": "https://sesameworkshop.org/wp-content/uploads/2023/03/Snuffy_bio-copy-667x500.jpg",
  "Squeaky the Duck": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_ernie-750x416.png",
  "Two-Headed Monster": "https://image.pollinations.ai/prompt/sesame%20street%20two-headed%20monster%20fuzzy%20purple%20character%20clean%20white%20background?width=400&height=400&nologo=true&model=turbo",
  "Roxie Marie": "https://image.pollinations.ai/prompt/sesame%20street%20roxie%20marie%20muppet%20female%20character%20clean%20white%20background?width=400&height=400&nologo=true&model=turbo"
};

export const CHARACTERS = Object.keys(OFFICIAL_IMAGES);

// 26 cards perfectly dispersed so id, upper, and lower metrics are independent!
export const CARD_DECK = [
  { id: 14, letterUpper: "A", letterLower: "m", character: "Abby Cadabby", food: "Mango", color: "bg-pink-400", palette: [{n:'Pink',c:'#ec4899'},{n:'Purple',c:'#a855f7'},{n:'Orange',c:'#f97316'}] },
  { id: 7, letterUpper: "B", letterLower: "x", character: "Baby Bear", food: "Xigua", color: "bg-yellow-400", palette: [{n:'Brown',c:'#a16207'},{n:'Green',c:'#22c55e'},{n:'Red',c:'#ef4444'}] },
  { id: 22, letterUpper: "C", letterLower: "f", character: "Cookie Monster", food: "Fig", color: "bg-blue-500", palette: [{n:'Blue',c:'#3b82f6'},{n:'Purple',c:'#7e22ce'},{n:'Green',c:'#16a34a'}] },
  { id: 3, letterUpper: "D", letterLower: "s", character: "Big Bird", food: "Spinach", color: "bg-purple-600", palette: [{n:'Yellow',c:'#eab308'},{n:'Pink',c:'#ec4899'},{n:'Green',c:'#15803d'}] },
  { id: 19, letterUpper: "E", letterLower: "b", character: "Elmo", food: "Broccoli", color: "bg-red-500", palette: [{n:'Red',c:'#ef4444'},{n:'Orange',c:'#f97316'},{n:'Green',c:'#16a34a'}] },
  { id: 11, letterUpper: "F", letterLower: "k", character: "Snuffy", food: "Kiwi", color: "bg-green-600", palette: [{n:'Brown',c:'#854d0e'},{n:'Green',c:'#65a30d'},{n:'Black',c:'#1c1917'}] },
  { id: 26, letterUpper: "G", letterLower: "p", character: "Grover", food: "Peach", color: "bg-blue-600", palette: [{n:'Blue',c:'#2563eb'},{n:'Pink',c:'#db2777'},{n:'Peach',c:'#ffedd5'}] },
  { id: 5, letterUpper: "H", letterLower: "u", character: "Oscar the Grouch", food: "Ugli Fruit", color: "bg-cyan-500", palette: [{n:'Green',c:'#22c55e'},{n:'Brown',c:'#78350f'},{n:'Lime',c:'#84cc16'}] },
  { id: 16, letterUpper: "I", letterLower: "d", character: "Ji-Young", food: "Dragon Fruit", color: "bg-green-400", palette: [{n:'Black',c:'#1c1917'},{n:'Magenta',c:'#d946ef'},{n:'White',c:'#ffffff'}] },
  { id: 8, letterUpper: "J", letterLower: "y", character: "Julia", food: "Yam", color: "bg-orange-500", palette: [{n:'Orange',c:'#f97316'},{n:'Yellow',c:'#fef08a'},{n:'Green',c:'#22c55e'}] },
  { id: 2, letterUpper: "K", letterLower: "h", character: "Cookie Monster", food: "Honeydew", color: "bg-emerald-500", palette: [{n:'Blue',c:'#3b82f6'},{n:'Light Green',c:'#bbf7d0'},{n:'White',c:'#ffffff'}] },
  { id: 24, letterUpper: "L", letterLower: "c", character: "Elmo", food: "Carrot", color: "bg-yellow-500", palette: [{n:'Red',c:'#ef4444'},{n:'Orange',c:'#f97316'},{n:'Green',c:'#16a34a'}] },
  { id: 9, letterUpper: "M", letterLower: "r", character: "Tamir", food: "Raspberry", color: "bg-orange-400", palette: [{n:'Brown',c:'#78350f'},{n:'Yellow',c:'#eab308'},{n:'Red',c:'#dc2626'}] },
  { id: 21, letterUpper: "N", letterLower: "a", character: "Ernie", food: "Apple", color: "bg-red-300", palette: [{n:'Orange',c:'#f97316'},{n:'Black',c:'#1c1917'},{n:'Red',c:'#ef4444'}] },
  { id: 13, letterUpper: "O", letterLower: "v", character: "Oscar", food: "Vine Tomato", color: "bg-green-700", palette: [{n:'Green',c:'#22c55e'},{n:'Silver',c:'#a8a29e'},{n:'Red',c:'#ef4444'}] },
  { id: 4, letterUpper: "P", letterLower: "i", character: "Mr. Snuffleupagus", food: "Iceberg Lettuce", color: "bg-pink-300", palette: [{n:'Brown',c:'#854d0e'},{n:'Pink',c:'#ec4899'},{n:'Light Green',c:'#bef264'}] },
  { id: 18, letterUpper: "Q", letterLower: "n", character: "Squeaky the Duck", food: "Nectarine", color: "bg-orange-300", palette: [{n:'Yellow',c:'#fbf08a'},{n:'Orange',c:'#f97316'},{n:'Red',c:'#ef4444'}] },
  { id: 1, letterUpper: "R", letterLower: "w", character: "Rosita", food: "Watermelon", color: "bg-teal-400", palette: [{n:'Turquoise',c:'#14b8a6'},{n:'Red',c:'#ef4444'},{n:'Green',c:'#22c55e'}] },
  { id: 12, letterUpper: "S", letterLower: "e", character: "Snuffy", food: "Eggplant", color: "bg-amber-600", palette: [{n:'Brown',c:'#854d0e'},{n:'Purple',c:'#9333ea'},{n:'Green',c:'#16a34a'}] },
  { id: 25, letterUpper: "T", letterLower: "j", character: "Telly", food: "Jalapeno", color: "bg-fuchsia-500", palette: [{n:'Magenta',c:'#d946ef'},{n:'Orange',c:'#f97316'},{n:'Green',c:'#22c55e'}] },
  { id: 10, letterUpper: "U", letterLower: "o", character: "Count von Count", food: "Orange", color: "bg-indigo-400", palette: [{n:'Purple',c:'#7e22ce'},{n:'Green',c:'#15803d'},{n:'Orange',c:'#f97316'}] },
  { id: 20, letterUpper: "V", letterLower: "t", character: "Count von Count", food: "Tomato", color: "bg-purple-500", palette: [{n:'Purple',c:'#7e22ce'},{n:'Black',c:'#1c1917'},{n:'Red',c:'#ef4444'}] },
  { id: 6, letterUpper: "W", letterLower: "z", character: "Two-Headed Monster", food: "Zucchini", color: "bg-rose-500", palette: [{n:'Purple',c:'#a855f7'},{n:'Horn',c:'#fef08a'},{n:'Green',c:'#22c55e'}] },
  { id: 15, letterUpper: "X", letterLower: "l", character: "Roxie Marie", food: "Lemon", color: "bg-red-600", palette: [{n:'Lime',c:'#84cc16'},{n:'Pink',c:'#ec4899'},{n:'Yellow',c:'#fef08a'}] },
  { id: 23, letterUpper: "Y", letterLower: "g", character: "Ji-Young", food: "Grape", color: "bg-teal-600", palette: [{n:'Black',c:'#1c1917'},{n:'Purple',c:'#9333ea'},{n:'Green',c:'#22c55e'}] },
  { id: 17, letterUpper: "Z", letterLower: "q", character: "Zoe", food: "Quince", color: "bg-orange-400", palette: [{n:'Orange',c:'#f97316'},{n:'Pink',c:'#ec4899'},{n:'Yellow',c:'#fef08a'}] },
];
