export const OFFICIAL_IMAGES: Record<string, string> = {
  "Abby Cadabby": "https://sesameworkshop.org/wp-content/uploads/2023/03/Abby-1-667x500.png",
  "Bert": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_bert-750x416.png",
  "Big Bird": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_bigbird-750x416.png",
  "Cookie Monster": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_cookiemonster-750x416.png",
  "Count von Count": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_count-750x416.png",
  "Elmo": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_elmo-750x416.png",
  "Ernie": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_ernie-750x416.png",
  "Grover": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_grover-750x416.png",
  "Julia": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_julia-750x416.png",
  "Oscar": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_oscar-750x416.png",
  "Oscar the Grouch": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_oscar-750x416.png",
  "Rosita": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_rosita-750x416.png",
  "Snuffy": "https://sesameworkshop.org/wp-content/uploads/2023/03/Snuffy_bio-copy-667x500.jpg",
  "Zoe": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_zoe-750x416.png",
  "Baby Bear": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_babybear-750x416.png",
  "Gabrielle": "https://sesameworkshop.org/wp-content/uploads/2023/06/Gabrielle_Character-750x416.png",
  "Gonger": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_gonger-750x416.png",
  "Ji-Young": "https://sesameworkshop.org/wp-content/uploads/2023/03/Ji-Young.Character-750x416.jpeg",
  "Rudy": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_rudy-750x416.png",
  "Tamir": "https://sesameworkshop.org/wp-content/uploads/2023/02/Tamir-667x500.jpg",
  "Telly": "https://sesameworkshop.org/wp-content/uploads/2023/02/presskit_ss_bio_telly-750x416.png",
  "Mr. Snuffleupagus": "https://sesameworkshop.org/wp-content/uploads/2023/03/Snuffy_bio-copy-667x500.jpg",
  "Squeaky the Duck": "https://sesameworkshop.org/wp-content/uploads/2023/03/presskit_ss_bio_ernie-750x416.png",
  "Two-Headed Monster": "https://image.pollinations.ai/prompt/sesame%20street%20two-headed%20monster%20fuzzy%20purple%20character%20clean%20white%20background?width=400&height=400&nologo=true",
  "Roxie Marie": "https://image.pollinations.ai/prompt/sesame%20street%20roxie%20marie%20muppet%20female%20character%20clean%20white%20background?width=400&height=400&nologo=true"
};

export const CHARACTERS = Object.keys(OFFICIAL_IMAGES);

// 26 cards perfectly dispersed so id, upper, and lower metrics are independent!
export const CARD_DECK = [
  { id: 14, letterUpper: "A", letterLower: "m", character: "Abby Cadabby", food: "Mango", color: "bg-pink-400" },
  { id: 7, letterUpper: "B", letterLower: "x", character: "Baby Bear", food: "Xigua", color: "bg-yellow-400" },
  { id: 22, letterUpper: "C", letterLower: "f", character: "Cookie Monster", food: "Fig", color: "bg-blue-500" },
  { id: 3, letterUpper: "D", letterLower: "s", character: "Big Bird", food: "Spinach", color: "bg-purple-600" },
  { id: 19, letterUpper: "E", letterLower: "b", character: "Elmo", food: "Broccoli", color: "bg-red-500" },
  { id: 11, letterUpper: "F", letterLower: "k", character: "Snuffy", food: "Kiwi", color: "bg-green-600" },
  { id: 26, letterUpper: "G", letterLower: "p", character: "Grover", food: "Peach", color: "bg-blue-600" },
  { id: 5, letterUpper: "H", letterLower: "u", character: "Oscar the Grouch", food: "Ugli Fruit", color: "bg-cyan-500" },
  { id: 16, letterUpper: "I", letterLower: "d", character: "Ji-Young", food: "Dragon Fruit", color: "bg-green-400" },
  { id: 8, letterUpper: "J", letterLower: "y", character: "Julia", food: "Yam", color: "bg-orange-500" },
  { id: 2, letterUpper: "K", letterLower: "h", character: "Cookie Monster", food: "Honeydew", color: "bg-emerald-500" },
  { id: 24, letterUpper: "L", letterLower: "c", character: "Elmo", food: "Carrot", color: "bg-yellow-500" },
  { id: 9, letterUpper: "M", letterLower: "r", character: "Tamir", food: "Raspberry", color: "bg-orange-400" },
  { id: 21, letterUpper: "N", letterLower: "a", character: "Ernie", food: "Apple", color: "bg-red-300" },
  { id: 13, letterUpper: "O", letterLower: "v", character: "Oscar", food: "Vine Tomato", color: "bg-green-700" },
  { id: 4, letterUpper: "P", letterLower: "i", character: "Mr. Snuffleupagus", food: "Iceberg Lettuce", color: "bg-pink-300" },
  { id: 18, letterUpper: "Q", letterLower: "n", character: "Squeaky the Duck", food: "Nectarine", color: "bg-orange-300" },
  { id: 1, letterUpper: "R", letterLower: "w", character: "Rosita", food: "Watermelon", color: "bg-teal-400" },
  { id: 12, letterUpper: "S", letterLower: "e", character: "Snuffy", food: "Eggplant", color: "bg-amber-600" },
  { id: 25, letterUpper: "T", letterLower: "j", character: "Telly", food: "Jalapeno", color: "bg-fuchsia-500" },
  { id: 10, letterUpper: "U", letterLower: "o", character: "Count von Count", food: "Orange", color: "bg-indigo-400" },
  { id: 20, letterUpper: "V", letterLower: "t", character: "Count von Count", food: "Tomato", color: "bg-purple-500" },
  { id: 6, letterUpper: "W", letterLower: "z", character: "Two-Headed Monster", food: "Zucchini", color: "bg-rose-500" },
  { id: 15, letterUpper: "X", letterLower: "l", character: "Roxie Marie", food: "Lemon", color: "bg-red-600" },
  { id: 23, letterUpper: "Y", letterLower: "g", character: "Ji-Young", food: "Grape", color: "bg-teal-600" },
  { id: 17, letterUpper: "Z", letterLower: "q", character: "Zoe", food: "Quince", color: "bg-orange-400" },
];
